// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('web_api_key'),
    appId: dotenv.get('web_app_id'),
    messagingSenderId: dotenv.get('messaging_sender_id'),
    projectId: dotenv.get('project_id'),
    authDomain: dotenv.get('auth_domain'),
    storageBucket: dotenv.get('storage_bucket'),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('android_api_key'),
    appId: dotenv.get('android_app_id'),
    messagingSenderId: dotenv.get('messaging_sender_id'),
    projectId: dotenv.get('project_id'),
    storageBucket: dotenv.get('storage_bucket'),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('ios_api_key'),
    appId: dotenv.get('ios_app_id'),
    messagingSenderId: dotenv.get('messaging_sender_id'),
    projectId: dotenv.get('project_id'),
    storageBucket: dotenv.get('storage_bucket'),
    iosBundleId: dotenv.get('ios_bundleId'),
  );
}
